### ISSUE TITLE
Document what `renovate.json` is for

### ISSUE THREAD

**Issue by Svish** [sanity-io/nextjs-blog-cms-sanity-v3#116]
Created a new project using this starter, and I find this `renovate.json` file in it, but I don't see any explanation of why it's here, what it's for, or how to use it.

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "github>sanity-io/renovate-presets//ecosystem/auto",
    "github>sanity-io/renovate-presets//ecosystem/studio-v3"
  ]
}
```

What does it do? Should it be deleted in my project? Or does it have value to me? If so, how? Do I need to set something up for it to "do anything"?

**Comment by stipsan** [comment]
Hey, we use it to get PRs for dependency updates 🙂 [If you don't install it first](https://github.com/apps/renovate), then this file does nothing.
If you do have it installed, then you'll see it open an issue like [this that keeps you posted on the status of your dependencies](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/issues/4). And PRs that helps keep you up to date on npm packages like `sanity`, `next-sanity` and more.

**Comment by stipsan** [comment]
Here's an example PR: https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/pull/112

**Comment by Svish** [comment]
Cool, need to check that out, could be useful for other projects too.

Would still like to encourage you guys to document that somehow in the starter though. Understanding the bits and pieces that are pulled in via a starter is crucial to not feel overwhelmed and confused.

In this case, it should be some short documentation of what Renovate is, that it's safe to delete the file if you don't want to use it, and what in the world _this_ actually does:

```
  "extends": [
    "github>sanity-io/renovate-presets//ecosystem/auto",
    "github>sanity-io/renovate-presets//ecosystem/studio-v3"
  ]
```

**Comment by stipsan** [comment]
Yup great suggestion @Svish, adding to the backlog 👍

**Comment by stipsan** [comment]
For now, there's more information on the preset we're using here: https://github.com/sanity-io/renovate-presets/tree/main/ecosystem#readme

```
  "extends": [
    "github>sanity-io/renovate-presets//ecosystem/auto",
    "github>sanity-io/renovate-presets//ecosystem/studio-v3"
  ]
```
This loads two presets:
- https://github.com/sanity-io/renovate-presets/blob/main/ecosystem/auto.json
- https://github.com/sanity-io/renovate-presets/blob/main/ecosystem/studio-v3.json

In these presets we try to fill out `description` fields for each rule to explain what they are and what they do :relaxed:
