### ISSUE TITLE
Bug: on-demand revalidation showing one step old stale data

### ISSUE THREAD

**Issue by surjithctly** [sanity-io/nextjs-blog-cms-sanity-v3#131]
I'm using the `api/revalidate` to update content. But each time it updates, it returns one step old data. Not fresh. 

I'm tried using both`useCdn:` true & false, but same result. Here, the webhook fires immediately after publishing, but apicdn takes upto 60 sec to update the content. Thus Next.js getting old data each time. 

See below video. 

### Video transcription:
Starts next production builds
change “first post” to “Our first post”
Simulate “webhook” requests
Data do not change

[next attempt]
change “Our first post” to “Next first post”
Data change to Stale “Our First post” this time
but new data is “Next First Post” (edited) 

https://user-images.githubusercontent.com/1884712/207079785-48b821f7-1da7-439b-a07c-665fcdbe3689.mp4

**Comment by surjithctly** [comment]
Are you able to reproduce this bug?

**Comment by surjithctly** [comment]
Are you able to reproduce this bug? @stipsan

**Comment by stipsan** [comment]
The revalidate function isn't designed to be used with `useCdn`. It should be `false` 🤔

**Comment by surjithctly** [comment]
Tried with both true & false. But same result.

**Comment by surjithctly** [comment]
Sure. here it is: https://github.com/surjithctly/jamstack-starter

**Comment by stipsan** [comment]
Thnx, I'm on the go right now and couldn't see anything out of the ordinary when browsing your code saw. Back home I'll investigate on my laptop and see what's going on

**Comment by surjithctly** [comment]
Thank you, I even tried adding a delay of 5 seconds in `revalidate.ts`, but that also did not help.

**Comment by surjithctly** [comment]
Damn! just realized I still had useCdn true for frontend, false was only applied for revalidate. 🤦‍♂️

It does seems to work now. ✅

Thanks a lot for the help. You may close this issue.

**Comment by stipsan** [comment]
Great to hear you figured it out @surjithctly! 😌 There's some more information on how the revalidation works in this thread: https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/issues/97#issuecomment-1325872464
