### ISSUE TITLE
Cannot find module '@sanity/ui'

### ISSUE THREAD

**Issue by enriqueiturriagaa** [sanity-io/nextjs-blog-cms-sanity-v3#154]
Keep getting this when I try to go to the /studio
Unhandled Runtime Error Error: Cannot find module '@sanity/ui'

The loader shows for a sec and the this happens. 

The studio worked for a couple of hours and then this started to happen. 

I tried installing @sanity/ui and nothing. 

Does anyone have a hint on how to solve this?

**Comment by stipsan** [comment]
Hi, until https://github.com/sanity-io/ui/pull/1038 is merged and released you can lock your `@sanity/ui` version to `1.0.4` 🙌

**Comment by ehowey** [comment]
I give an answer to temporarily fix this with yarn resolutions if that is easier for you here: https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/issues/155#issuecomment-1368212781
