### ISSUE TITLE
Type error: Property 'token' does not exist on type 'PreviewData'.

### ISSUE THREAD

**Issue by benjosity** [sanity-io/nextjs-blog-cms-sanity-v3#183]
After deploying from Vercel and following the Readme for pulling environment variables I'm unable to run the build process 

<img width="826" alt="Screenshot 2023-01-14 at 16 05 24" src="https://user-images.githubusercontent.com/5020948/212481901-db81fdd3-cc6d-4fa8-a689-83c5dd924a17.png">

**Comment by agonist** [comment]
also happening in `posts/page.tsx`

**Comment by stipsan** [comment]
Yeah the typings is changed in next13 so you'll now have to refactor to `(previewData() as unknown as {token?: string})` 😅
