### ISSUE TITLE
Running into some issues when setting up new project

### ISSUE THREAD

**Issue by rupakhetibinit** [sanity-io/nextjs-blog-cms-sanity-v3#185]
I followed the tutorial and I am running into some weird errors. I managed to deploy the sanity studio but on development and production it breaks with this specific error when navigating to settings

```Error: (0 , react__WEBPACK_IMPORTED_MODULE_4__.cache) is not a function
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_4__.cache) is not a function
    at eval (webpack-internal:///./schemas/settings/OpenGraphPreview.tsx:36:58)
    at ./schemas/settings/OpenGraphPreview.tsx (http://localhost:3000/_next/static/chunks/schemas_settings_OpenGraphPreview_tsx.js:102:1)
    at options.factory (http://localhost:3000/_next/static/chunks/webpack.js?ts=1673877926238:698:31)
    at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js?ts=1673877926238:37:33)
    at Function.fn (http://localhost:3000/_next/static/chunks/webpack.js?ts=1673877926238:353:21)
```

The specific thing that is failing is the cache function that is imported from react in OpenGraphPreview.tsx. Any idea what might be going wrong?

**Comment by korompaiistvan** [comment]
these functions are added by the next runtime, see node_modules/next/types/index.d.ts

```ts
// Extend the React types with missing properties
declare module 'react' {
  // <html amp=""> support
  interface HtmlHTMLAttributes<T> extends React.HTMLAttributes<T> {
    amp?: string
  }

  // <link nonce=""> support
  interface LinkHTMLAttributes<T> extends HTMLAttributes<T> {
    nonce?: string
  }

  function use<T>(promise: Promise<T> | React.Context<T>): T
  function cache<T extends Function>(fn: T): T
}
```

it seems that through their close working relationship with the core react team they added these earlier to the experimental-edge runtime.

that means that they should work in theory (and they actually do on my end).

**Comment by korompaiistvan** [comment]
I could reproduce your issue by following the steps in the readme. It seems the issue is that these functions are only available with the nextjs appDir function that's currently in beta, and this template has moved off it today.

so this was caused by #186 but the long-term fix would be to remove the use of `use()` and `cache()` from the `OpenGraphPreview` component.

a short-term workaround is to remove line 58-75 from the `schemas/settings/index.ts` file. those lines are:
```js
    defineField({
      name: 'ogImage',
      title: 'Open Graph Image',
      description:
        'Used for social media previews when linking to the index page.',
      type: 'object',
      components: {
        input: OpenGraphInput as any,
      },
      fields: [
        defineField({
          name: 'title',
          title: 'Title',
          type: 'string',
          initialValue: demo.ogImageTitle,
        }),
      ],
    }),
```

this will remove the offending component from the settings page
