### ISSUE TITLE
"Loading... Click here to exit preview mode." incorrectly displayed on all Post pages

### ISSUE THREAD

**Issue by simonhrogers** [sanity-io/nextjs-blog-cms-sanity-v3#194]
`loading` and `preview` are passed as props to the non-preview instance of the component, do they need to be?

```
  return (
    <PostPage
      loading
      preview
      post={post}
      morePosts={morePosts}
      settings={settings}
    />
  )
```

this results in screenshot attached at all times:

<img width="1389" alt="Screenshot 2023-01-19 at 17 14 40" src="https://user-images.githubusercontent.com/12583581/213517780-5fb267a0-33c7-4d9b-a2ae-7f425d968459.png">

This is using the latest commit – `f5090d0` at time of writing. 

Thanks!

**Comment by stipsan** [comment]
That's indeed a recent regression! 😱
