### ISSUE TITLE
Bug with Image Upload -- field gets unset

### ISSUE THREAD

**Issue by brendenmoore** [sanity-io/nextjs-blog-cms-sanity-v3#298]
I was able to reproduce this with a brand new clone/deployment of this starter.

The issue is when trying to upload an image, the upload is successful, but the asset is not added to the document. Or rather, it is, but then the field is unset.

Steps to reproduce:
1. Click "Deploy" and begin a brand new copy of this project, link to a new sanity project. Don't even worry about pulling it locally, it's reproducible in prod.
2. Open the deployed sanity studio and go to "Authors"
3. Try to upload an image. 

Notes:
- The image _does_ get uploaded. You can see it if you click on "Select" and "Uploaded Images". You can even then add it from that screen and it works successfully.
- I captured the following payload from the post request that goes to sanity after the image upload. It appears that the field is getting unset for some reason. 
- I am using Chrome browser for this, if that makes a difference.

```
{
    "mutations": [
        {
            "createIfNotExists": {
                "_id": "drafts.08ca9206-21a3-4bab-890e-6d4b9689efad",
                "_type": "author"
            }
        },
        {
            "patch": {
                "setIfMissing": {
                    "picture": {
                        "_type": "image"
                    }
                },
                "id": "drafts.08ca9206-21a3-4bab-890e-6d4b9689efad"
            }
        },
        {
            "patch": {
                "id": "drafts.08ca9206-21a3-4bab-890e-6d4b9689efad",
                "set": {
                    "picture.asset": {
                        "_type": "reference",
                        "_ref": "image-4f79056bcc6061b865979e057fbd0904a7cc03e1-1280x720-png"
                    }
                }
            }
        },
        {
            "patch": {
                "id": "drafts.08ca9206-21a3-4bab-890e-6d4b9689efad",
                "diffMatchPatch": {
                    "picture._upload.updatedAt": "@@ -15,10 +15,10 @@\n 11:2\n-4.396\n+5.454\n Z\n"
                }
            }
        },
        {
            "patch": {
                "unset": [
                    "picture"
                ],
                "id": "drafts.08ca9206-21a3-4bab-890e-6d4b9689efad"
            }
        },
        {
            "patch": {
                "unset": [
                    "picture"
                ],
                "id": "drafts.08ca9206-21a3-4bab-890e-6d4b9689efad"
            }
        }
    ],
    "transactionId": "56cf936b-5e83-4135-8b19-5ac86985611f"
}
```

**Comment by stipsan** [comment]
[This bug were resolved in `sanity` v3.11.2](https://github.com/sanity-io/sanity/releases/tag/v3.11.2)
