### ISSUE TITLE
isValidSignature always fails 

### ISSUE THREAD

**Issue by jasan-s** [sanity-io/nextjs-blog-cms-sanity-v3#330]
For some reason my revalidation endpoint always throws an invalid signature error. I have confirmed my secret in sanity webhook matches the env variable value. 

The signature is within the header. 
The secret exists in the env

Can you provide any suggestions? 
How exactly can I debug this?

**Comment by jasan-s** [comment]
I found the issue but still don't know how to solve it.

I am using firebase hosting to deploy the app. 

In production deployed environment the body is empty empty string. 
It works locally.

**Comment by Codeshark-NET** [comment]
Hey @jasan-s , would you be able to post the full error info? Thanks! It could likely be related to the firebase environment.
