### ISSUE TITLE
/app directory version

### ISSUE THREAD

**Issue by laurosilvacom** [sanity-io/nextjs-blog-cms-sanity-v3#360]
When will this template be migrated to use the [/app](https://beta.nextjs.org/docs/routing/fundamentals#the-app-directory) directory? Happy to provide support if existing efforts are underway 🫶

**Comment by oryouormeorwe** [comment]
Chiming in on this. The project I've developed on top of this template seems that it could benefit from the migrating to the app directory.

According to this the app directory is considered stable as of May 4th 2023 https://github.com/vercel/next.js/discussions/41745#discussioncomment-5809024!

**Comment by owenhoskins** [comment]
Chiming in... The project I've developed on top of this template seems that it could benefit from the migrating to the app directory.

According to this discussion the app directory is considered stable as of May 4th 2023: https://github.com/vercel/next.js/discussions/41745#discussioncomment-5809024!

@stipsan would you offer some input on this?

**Comment by medkrimi** [comment]
@laurosilvacom I have seen there is some progress on the app directory here: https://github.com/sanity-io/template-nextjs-personal-website.

**Comment by guylepage3** [comment]
Is this happening or is this repository dead?
