### ISSUE TITLE
Revalidate webhook config link not working

### ISSUE THREAD

**Issue by stephenarra** [sanity-io/nextjs-blog-cms-sanity-v3#49]
I tried using the shared config link for the revalidate webhook and ran into an internal server error until removing the dash from the webhook name. Not sure if sanity is suppose to allow dashes in webhook names, but may want to remove the dash in the config url (eg. `name=On+demand+Revalidation`).

**Comment by brantchoate** [comment]
I think same issue for me

<img width="721" alt="image" src="https://user-images.githubusercontent.com/1505708/199799476-2e573229-0b6d-46f9-afd6-c50cdecea889.png">

**Comment by tudormunteanu** [comment]
My webhooks are not called at all. That `["post", "author", "settings"] in _type` looks fishy to me. Is it valid GROQ?

**Comment by stipsan** [comment]
Hi @stephenarra and @tudormunteanu, after extensive testing we've [updated the guide](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/blob/f15a943ce70183ad3cb1b0a4a4371b58e0f228c4/pages/api/revalidate.tsx#L7-L20) to reflect what we have working in production on our own sites. :relaxed:

@brantchoate seems like you're experiencing a bug in our [Vercel Integration](https://vercel.com/integrations/sanity). Do you mind opening a new issue with some more info to help us reproduce?
Your login provider: Google, GitHub or Sanity.
Your browser version, platform and if you're using incognito mode.
If you've used the Vercel Integration before or if this is your first time.
And does it happen if you [try again](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fsanity-io%2Fnextjs-blog-cms-sanity-v3&repository-name=blog-nextjs-sanity&project-name=blog-nextjs-sanity&demo-title=Blog%20with%20Built-in%20Content%20Editing&demo-description=A%20Sanity-powered%20blog%20with%20built-in%20content%20editing%20%26%20instant%20previews&demo-url=https%3A%2F%2Fnextjs-blog.sanity.build%2F%3Futm_source%3Dvercel%26utm_medium%3Dreferral&demo-image=https%3A%2F%2Fuser-images.githubusercontent.com%2F81981%2F197501516-c7c8092d-0305-4abe-afb7-1e896ef7b90a.png&integration-ids=oac_hb2LITYajhRQ0i4QznmKH7gx&external-id=nextjs;template=nextjs-blog-cms-sanity-v3) on the latest version?
