### ISSUE TITLE
Multiple features not working

### ISSUE THREAD

**Issue by mediabeastnz** [sanity-io/nextjs-blog-cms-sanity-v3#76]
Given this is a template example, I feel it should be somewhat usable. However it seems some key features listed don't work.

Live preview - doesn't automatically refresh when changes are made in the editor
Document Actions - this doesn't work as it is in this example, it seems that can only be done via definePlugins

**Comment by tudormunteanu** [comment]
I second this

**Comment by stipsan** [comment]
Hi @mediabeastnz & @tudormunteanu :relaxed:

We've pushed some fixes to the starter that address Live Preview in particular, as well as the mentioned `Document Actions` bug 😌
