### ISSUE TITLE
Unhandled error on preview

### ISSUE THREAD

**Issue by stitot** [sanity-io/nextjs-blog-cms-sanity-v3#79]
I've imported some other document types into this template other than author, post and settings. Everything worked fine, but after the import I get the unhandled error below when trying to preview documents of type post. The studio is working fine other than this, and I'm able to add and edit all document types.

```
groq-store.modern.mjs?1b67:1 Uncaught (in promise) Error: Error streaming dataset: Reached limit of 3000 documents
    at m (groq-store.modern.mjs?1b67:1:2878)
    at async EventSource.open (groq-store.modern.mjs?1b67:1:4645)
```

**Comment by stipsan** [comment]
We released a new version of `next-sanity` [yesterday](https://github.com/sanity-io/next-sanity/releases/tag/v1.1.0), if you upgrade to it you'll be able to use new [`includeTypes`](https://github.com/sanity-io/next-sanity/blob/v1.1.0/README.md#usage:~:text=local%20groq%2Dstore.-,includeTypes,-%3A%20%5B%27page) option to limit the size of the dataset that is exported locally.
You can also try increasing `documentLimit`. Both options are added here: https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/blob/69f2ab3f4a3f14a73f8c415eae6fe1889803e812/lib/config.tsx

**Comment by stitot** [comment]
Wow, it works like a charm, @stipsan !! Just in time. Thanks!!
