### ISSUE TITLE
Revalidate "More stories" with a webhook doesn't always work when adding/removing a post

### ISSUE THREAD

**Issue by tddostu** [sanity-io/nextjs-blog-cms-sanity-v3#93]
Related Commit 9c45983a5e97c2621daae7251d0356f856594196 (https://nextjs-blog-cms-sanity-v3-m2zs0oidy.sanity.build).

_Originally posted by @kmelve in https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/issues/89#issuecomment-1321304197_

### Summary

When updating a post or author, revalidation works as expected across the homepage and existing posts. However, when adding or removing/unpublishing a post entirely, sometimes only the homepage path gets revalidated. This means the "More stories" section on other exisiting posts doesn't get updated. The deleted/unpublished post also gets left behind and is still accessible. 

Sometimes it _does_ work, I can't seem to figure out why. 

### Video attached shows:

- Newly deployed site using the deploy button in this repo (as at [e43759b](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/commit/e43759b0c963ce357cf613702f176c257a4c02fc))
- Site with 4 posts with a new 5th post being published, validation of home + all existing posts works (as seen in the function logs on the left)
- When deleting that 5th post, only the homepage is invalidated, leaving the "More stories" section on all other posts out of date + the removed post still available
- Adding another new post (Test Post 06), only the homepage gets revalidated, the new post is missing from "More Stories" on all other posts
- Unpublishing an existing post (Test Post 04) only invalidates the homepage and itself, leaving it in the "More Stories" section on most other posts 

### Expected behaviour:

- Adding a new post should add it to the "More stories" section of all other posts. 
  - Note that this _does_ reliably happen for me when updating a post, making a new post and then updating it immediately after is my current workaround
- Removing/Unpublishing a post should:
  - remove it from the "More stories" section of all other posts
  - make it inaccessible from the website as a whole.

https://user-images.githubusercontent.com/36751136/203326802-a09fd61c-05d9-454b-9ed8-e9dcaf23bf5e.mp4

**Comment by stipsan** [comment]
First of all, thank you for the super detailed report! 🙌  Secondly, I have to admit I didn't think about the delete case when writing the new logic 🙈  

It really helps that you spent all this effort investigating and sharing your findings 🙇

**Comment by stipsan** [comment]
Ok should be solved now @tddostu 😄 If it's not, feel free to reopen! :relaxed:
